# Generated by Django 5.1.4 on 2024-12-12 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0002_remove_user_categorys_remove_user_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
